### ISSUE TITLE
Reporting wrong host

### ISSUE THREAD

**Issue by lejsekt** [natemcmaster/dotnet-serve#131]
**Describe the bug**
dotnet serve reports a wrong host (or perhaps does not report all the host that it is serving on).

**To Reproduce**
dotnet serve --address 0.0.0.0

Output in the terminal:

Starting server, serving .
Listening on:
  http://localhost:37161

But it is possible to reach it on all the network interfaces.

**Expected behavior**
Listening on should be http://0.0.0.0:3761 or all the hosts should be reported.

Thank you.

**Comment by natemcmaster** [comment]
0.0.0.0 is a special cased because of https://github.com/natemcmaster/dotnet-serve/issues/6.
https://github.com/natemcmaster/dotnet-serve/blob/f0e798616d96d190d0d5273871c809515a0c311c/src/dotnet-serve/SimpleServer.cs#L136-L143

The server running is actually running on IPAny, but it's just not what we print to the console because that makes the link un-clickable for Windows developers.

**Comment by lejsekt** [comment]
I see. But how about adjusting the message? Such as "Listening on any IP:". Or adding something after http://localhost:{port} such as "(and on any IP as well)"?

**Comment by natemcmaster** [comment]
That seems like a good update. Would you be willing to make a pull request for that?

**Comment by lejsekt** [comment]
Yes: https://github.com/natemcmaster/dotnet-serve/pull/133
